web:
  build: ./docker/web
  container_name: "api_web"
  ports:
    - "8080:80"
  volumes:
    - ./:/code
    - ./docker/web/api.conf:/etc/nginx/conf.d/site.conf
    - ./log/nginx:/var/log/nginx
  links:
    - app
    - db
app:
  build: ./docker/app
  container_name: "api_app"
  environment:
    XDEBUG_CONFIG: remote_host=${REMOTE_HOST_DBG}
    PHP_IDE_CONFIG: "serverName=HT Server"
  volumes:
    - ./:/code
  links:
    - db
composer:
  build: ./docker/composer
  container_name: "api_composer"
  command: composer update
  volumes_from:
  - app
db:
  image: mysql:5.7
  container_name: "api_mysql"
  environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${DB_DATABASE}
  volumes:
  - ./docker/data:/var/lib/mysql
  ports:
    - "3306:3306"