web:
  build: ./docker/web
  container_name: "media_web"
  ports:
    - "8080:80"
  volumes:
    - ./:/code
    - ./docker/web/api.conf:/etc/nginx/conf.d/site.conf
    - ./docker/log/nginx:/var/log/nginx
  links:
    - app
app:
  build: ./docker/app
  container_name: "media_app"
  environment:
    XDEBUG_CONFIG: remote_host=${REMOTE_HOST_DBG}
    PHP_IDE_CONFIG: "serverName=Media Server"
  volumes:
    - ./:/code
composer:
  build: ./docker/composer
  container_name: "media_composer"
  command: composer update
  volumes_from:
  - app